CREATE TABLE CPUs (
  Id SERIAL PRIMARY KEY,
  Nome TEXT NOT NULL,
  Fabricante TEXT NOT NULL,
  Socket TEXT NOT NULL,
  TDP INTEGER NOT NULL
);

CREATE TABLE GPUs (
  Id SERIAL PRIMARY KEY,
  Nome TEXT NOT NULL,
  TDP INTEGER NOT NULL,
  ConsumoRecomendado INTEGER NOT NULL,
  Comprimento INTEGER NOT NULL
);

CREATE TABLE Motherboards (
  Id SERIAL PRIMARY KEY,
  Nome TEXT NOT NULL,
  Socket TEXT NOT NULL,
  TipoRamSuportado TEXT NOT NULL,
  CapacidadeMaximaRam INTEGER NOT NULL,
  SlotsRam INTEGER NOT NULL
);

CREATE TABLE PSUs (
  Id SERIAL PRIMARY KEY,
  Nome TEXT NOT NULL,
  Potencia INTEGER NOT NULL,
  Certificacao TEXT NOT NULL
);

CREATE TABLE RAMs (
  Id SERIAL PRIMARY KEY,
  Nome TEXT NOT NULL,
  Tipo TEXT NOT NULL,
  Capacidade INTEGER NOT NULL,
  QuantidadeModulos INTEGER NOT NULL
);

CREATE TABLE Usuarios (
  Id SERIAL PRIMARY KEY,
  Nome TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  Senha TEXT NOT NULL,
  Admin BOOLEAN NOT NULL DEFAULT FALSE
);